# ConfigMap (Wave 0 - Default)
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-app6
  labels:
    app: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Default wave, can be omitted.
data:
  app-config: |
    key: value

---
# Deployment (Wave 1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app6
  labels:
    app: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # This will sync after the ConfigMap.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: app-config

---
# Service (Wave 2)
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-app6
  labels:
    app: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # This will sync after the Deployment.
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

