---
apiVersion: v1
kind: Namespace
metadata:
  name: pgdatabase
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: pgdatabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust the size as needed
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pgdatabase
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pgdatabase
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: myuser  # Replace with your desired username
            - name: POSTGRES_PASSWORD
              value: mypassword  # Replace with your desired password
            - name: POSTGRES_DB
              value: mydatabase  # Replace with your desired database name
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata  # Use a subdirectory for the data
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dvincent.ssm@gmail.com  # Updated email address
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-happynoises-work-tls
  namespace: pgdatabase
spec:
  secretName: wildcard-happynoises-work-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.happynoises.work"
  dnsNames:
    - "*.happynoises.work"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: pgdatabase
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: pgdatabase-https-redirect@kubernetescrd
spec:
  rules:
    - host: database.happynoises.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgres
                port:
                  number: 5432
  tls:
    - hosts:
        - database.happynoises.work
      secretName: wildcard-happynoises-work-tls
